### ISSUE TITLE
Error in scripts/parse-bbc-html-data.py

### ISSUE THREAD

**Issue by mittu1008** [shashiongithub/XSum#28]
(2.7.18/envs/venv) mittu1008@katfuji-7:~/XSum/XSum-Dataset$ python -m scripts/parse-bbc-html-data
226711
Traceback (most recent call last):
  File "/home/mittu1008/.pyenv/versions/2.7.18/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/mittu1008/.pyenv/versions/2.7.18/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mittu1008/XSum/XSum-Dataset/scripts/parse-bbc-html-data.py", line 198, in <module>
    story_title, story_introduction, story_restcontent = GenerateMapper((webarxivid, "bbc", htmldata))
  File "/home/mittu1008/XSum/XSum-Dataset/scripts/parse-bbc-html-data.py", line 143, in GenerateMapper
    story_title = ParseHtml(raw_story, corpus).getstory_title()
  File "/home/mittu1008/XSum/XSum-Dataset/scripts/parse-bbc-html-data.py", line 44, in __init__
    self.parser = html.HTMLParser(encoding=chardet.detect(self.story.html)['encoding'])
  File "/home/mittu1008/.pyenv/versions/2.7.18/envs/venv/lib/python2.7/site-packages/lxml/html/__init__.py", line 1910, in __init__
    super(HTMLParser, self).__init__(**kwargs)
  File "src/lxml/parser.pxi", line 1728, in lxml.etree.HTMLParser.__init__
  File "src/lxml/parser.pxi", line 840, in lxml.etree._BaseParser.__init__
LookupError: unknown encoding: 'IBM852'
(2.7.18/envs/venv)

what should I do to thi error?

**Comment by mittu1008** [comment]
Just my install way is not correct
